pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t my_python_app:latest .'
            }
        }
        stage('Run Tests') {
            steps {
                sh 'docker run --rm my_python_app:latest pytest tests/'
            }
        }
        stage('Deploy Application') {
            steps {
                sh 'docker-compose up -d'
            }
        }
    }
}